# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Thu Feb 23 13:44:23 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(560, 612)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 521, 471))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.groupBox = QtGui.QGroupBox(self.tab_1)
        self.groupBox.setGeometry(QtCore.QRect(19, 29, 121, 111))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 81, 68))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_6.addWidget(self.label)
        self.spinBox_1 = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_1.setMaximum(99999)
        self.spinBox_1.setProperty("value", 500)
        self.spinBox_1.setObjectName(_fromUtf8("spinBox_1"))
        self.verticalLayout_6.addWidget(self.spinBox_1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_1)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 160, 471, 111))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 30, 81, 68))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_9.addWidget(self.label_4)
        self.spinBox_4 = QtGui.QSpinBox(self.verticalLayoutWidget_4)
        self.spinBox_4.setMaximum(99999999)
        self.spinBox_4.setProperty("value", 210000)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.verticalLayout_9.addWidget(self.spinBox_4)
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(100, 30, 81, 68))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_10.addWidget(self.label_5)
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_5)
        self.doubleSpinBox_5.setSpecialValueText(_fromUtf8(""))
        self.doubleSpinBox_5.setDecimals(5)
        self.doubleSpinBox_5.setSingleStep(0.001)
        self.doubleSpinBox_5.setProperty("value", 0.12429)
        self.doubleSpinBox_5.setObjectName(_fromUtf8("doubleSpinBox_5"))
        self.verticalLayout_10.addWidget(self.doubleSpinBox_5)
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(180, 30, 81, 68))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_11.addWidget(self.label_6)
        self.doubleSpinBox_6 = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_6)
        self.doubleSpinBox_6.setReadOnly(True)
        self.doubleSpinBox_6.setDecimals(3)
        self.doubleSpinBox_6.setSingleStep(0.001)
        self.doubleSpinBox_6.setObjectName(_fromUtf8("doubleSpinBox_6"))
        self.verticalLayout_11.addWidget(self.doubleSpinBox_6)
        self.verticalLayoutWidget_7 = QtGui.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(260, 30, 81, 69))
        self.verticalLayoutWidget_7.setObjectName(_fromUtf8("verticalLayoutWidget_7"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_12.addWidget(self.label_7)
        self.doubleSpinBox_7 = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_7)
        self.doubleSpinBox_7.setReadOnly(True)
        self.doubleSpinBox_7.setDecimals(1)
        self.doubleSpinBox_7.setSingleStep(0.1)
        self.doubleSpinBox_7.setObjectName(_fromUtf8("doubleSpinBox_7"))
        self.verticalLayout_12.addWidget(self.doubleSpinBox_7)
        self.verticalLayoutWidget_8 = QtGui.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(340, 30, 81, 69))
        self.verticalLayoutWidget_8.setObjectName(_fromUtf8("verticalLayoutWidget_8"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_13.addWidget(self.label_8)
        self.doubleSpinBox_8 = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_8)
        self.doubleSpinBox_8.setReadOnly(True)
        self.doubleSpinBox_8.setDecimals(1)
        self.doubleSpinBox_8.setSingleStep(0.1)
        self.doubleSpinBox_8.setObjectName(_fromUtf8("doubleSpinBox_8"))
        self.verticalLayout_13.addWidget(self.doubleSpinBox_8)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_1)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 300, 321, 111))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayoutWidget_9 = QtGui.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(20, 30, 81, 68))
        self.verticalLayoutWidget_9.setObjectName(_fromUtf8("verticalLayoutWidget_9"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_14.setMargin(0)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget_9)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_14.addWidget(self.label_9)
        self.doubleSpinBox_9 = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_9)
        self.doubleSpinBox_9.setReadOnly(False)
        self.doubleSpinBox_9.setSingleStep(0.01)
        self.doubleSpinBox_9.setProperty("value", 0.0)
        self.doubleSpinBox_9.setObjectName(_fromUtf8("doubleSpinBox_9"))
        self.verticalLayout_14.addWidget(self.doubleSpinBox_9)
        self.verticalLayoutWidget_10 = QtGui.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(120, 30, 81, 69))
        self.verticalLayoutWidget_10.setObjectName(_fromUtf8("verticalLayoutWidget_10"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_15.setMargin(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget_10)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_15.addWidget(self.label_10)
        self.doubleSpinBox_10 = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_10)
        self.doubleSpinBox_10.setReadOnly(True)
        self.doubleSpinBox_10.setDecimals(1)
        self.doubleSpinBox_10.setSingleStep(0.1)
        self.doubleSpinBox_10.setObjectName(_fromUtf8("doubleSpinBox_10"))
        self.verticalLayout_15.addWidget(self.doubleSpinBox_10)
        self.verticalLayoutWidget_11 = QtGui.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(220, 30, 81, 69))
        self.verticalLayoutWidget_11.setObjectName(_fromUtf8("verticalLayoutWidget_11"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_16.setMargin(0)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget_11)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_16.addWidget(self.label_11)
        self.doubleSpinBox_11 = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_11)
        self.doubleSpinBox_11.setReadOnly(True)
        self.doubleSpinBox_11.setDecimals(1)
        self.doubleSpinBox_11.setObjectName(_fromUtf8("doubleSpinBox_11"))
        self.verticalLayout_16.addWidget(self.doubleSpinBox_11)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_1)
        self.groupBox_4.setGeometry(QtCore.QRect(170, 30, 241, 111))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 81, 68))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_7.addWidget(self.label_2)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.doubleSpinBox_2.setReadOnly(True)
        self.doubleSpinBox_2.setDecimals(1)
        self.doubleSpinBox_2.setSingleStep(0.1)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.verticalLayout_7.addWidget(self.doubleSpinBox_2)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(130, 30, 81, 68))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_8.addWidget(self.label_3)
        self.spinBox_3 = QtGui.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_3.setMaximum(99999)
        self.spinBox_3.setProperty("value", 6)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.verticalLayout_8.addWidget(self.spinBox_3)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_1)
        self.groupBox_6.setGeometry(QtCore.QRect(370, 300, 121, 111))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayoutWidget_12 = QtGui.QWidget(self.groupBox_6)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(20, 30, 81, 68))
        self.verticalLayoutWidget_12.setObjectName(_fromUtf8("verticalLayoutWidget_12"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_17.setMargin(0)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.label_12 = QtGui.QLabel(self.verticalLayoutWidget_12)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_17.addWidget(self.label_12)
        self.doubleSpinBox_12 = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_12)
        self.doubleSpinBox_12.setReadOnly(True)
        self.doubleSpinBox_12.setDecimals(1)
        self.doubleSpinBox_12.setSingleStep(0.1)
        self.doubleSpinBox_12.setObjectName(_fromUtf8("doubleSpinBox_12"))
        self.verticalLayout_17.addWidget(self.doubleSpinBox_12)
        self.tabWidget.addTab(self.tab_1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 40, 451, 341))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayoutWidget_15 = QtGui.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(240, 30, 81, 69))
        self.verticalLayoutWidget_15.setObjectName(_fromUtf8("verticalLayoutWidget_15"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.verticalLayoutWidget_15)
        self.verticalLayout_20.setMargin(0)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.label_15 = QtGui.QLabel(self.verticalLayoutWidget_15)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_20.addWidget(self.label_15)
        self.spinBox_15 = QtGui.QSpinBox(self.verticalLayoutWidget_15)
        self.spinBox_15.setMaximum(999)
        self.spinBox_15.setProperty("value", 8)
        self.spinBox_15.setObjectName(_fromUtf8("spinBox_15"))
        self.verticalLayout_20.addWidget(self.spinBox_15)
        self.verticalLayoutWidget_17 = QtGui.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_17.setGeometry(QtCore.QRect(130, 140, 81, 68))
        self.verticalLayoutWidget_17.setObjectName(_fromUtf8("verticalLayoutWidget_17"))
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.verticalLayoutWidget_17)
        self.verticalLayout_22.setMargin(0)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.label_17 = QtGui.QLabel(self.verticalLayoutWidget_17)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_22.addWidget(self.label_17)
        self.spinBox_18 = QtGui.QSpinBox(self.verticalLayoutWidget_17)
        self.spinBox_18.setMaximum(99)
        self.spinBox_18.setProperty("value", 3)
        self.spinBox_18.setObjectName(_fromUtf8("spinBox_18"))
        self.verticalLayout_22.addWidget(self.spinBox_18)
        self.verticalLayoutWidget_14 = QtGui.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(130, 30, 81, 68))
        self.verticalLayoutWidget_14.setObjectName(_fromUtf8("verticalLayoutWidget_14"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_19.setMargin(0)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.label_14 = QtGui.QLabel(self.verticalLayoutWidget_14)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_19.addWidget(self.label_14)
        self.spinBox_14 = QtGui.QSpinBox(self.verticalLayoutWidget_14)
        self.spinBox_14.setMaximum(999999)
        self.spinBox_14.setProperty("value", 4000)
        self.spinBox_14.setObjectName(_fromUtf8("spinBox_14"))
        self.verticalLayout_19.addWidget(self.spinBox_14)
        self.verticalLayoutWidget_23 = QtGui.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_23.setGeometry(QtCore.QRect(350, 30, 81, 69))
        self.verticalLayoutWidget_23.setObjectName(_fromUtf8("verticalLayoutWidget_23"))
        self.verticalLayout_28 = QtGui.QVBoxLayout(self.verticalLayoutWidget_23)
        self.verticalLayout_28.setMargin(0)
        self.verticalLayout_28.setObjectName(_fromUtf8("verticalLayout_28"))
        self.label_23 = QtGui.QLabel(self.verticalLayoutWidget_23)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_28.addWidget(self.label_23)
        self.spinBox_16 = QtGui.QSpinBox(self.verticalLayoutWidget_23)
        self.spinBox_16.setReadOnly(True)
        self.spinBox_16.setObjectName(_fromUtf8("spinBox_16"))
        self.verticalLayout_28.addWidget(self.spinBox_16)
        self.verticalLayoutWidget_19 = QtGui.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_19.setGeometry(QtCore.QRect(350, 140, 81, 69))
        self.verticalLayoutWidget_19.setObjectName(_fromUtf8("verticalLayoutWidget_19"))
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.verticalLayoutWidget_19)
        self.verticalLayout_24.setMargin(0)
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.label_19 = QtGui.QLabel(self.verticalLayoutWidget_19)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_24.addWidget(self.label_19)
        self.doubleSpinBox_20 = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_19)
        self.doubleSpinBox_20.setSingleStep(0.01)
        self.doubleSpinBox_20.setProperty("value", 0.3)
        self.doubleSpinBox_20.setObjectName(_fromUtf8("doubleSpinBox_20"))
        self.verticalLayout_24.addWidget(self.doubleSpinBox_20)
        self.verticalLayoutWidget_21 = QtGui.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_21.setGeometry(QtCore.QRect(130, 250, 81, 68))
        self.verticalLayoutWidget_21.setObjectName(_fromUtf8("verticalLayoutWidget_21"))
        self.verticalLayout_26 = QtGui.QVBoxLayout(self.verticalLayoutWidget_21)
        self.verticalLayout_26.setMargin(0)
        self.verticalLayout_26.setObjectName(_fromUtf8("verticalLayout_26"))
        self.label_21 = QtGui.QLabel(self.verticalLayoutWidget_21)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_26.addWidget(self.label_21)
        self.doubleSpinBox_22 = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_21)
        self.doubleSpinBox_22.setDecimals(3)
        self.doubleSpinBox_22.setSingleStep(0.001)
        self.doubleSpinBox_22.setProperty("value", 0.129)
        self.doubleSpinBox_22.setObjectName(_fromUtf8("doubleSpinBox_22"))
        self.verticalLayout_26.addWidget(self.doubleSpinBox_22)
        self.verticalLayoutWidget_22 = QtGui.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_22.setGeometry(QtCore.QRect(240, 250, 81, 68))
        self.verticalLayoutWidget_22.setObjectName(_fromUtf8("verticalLayoutWidget_22"))
        self.verticalLayout_27 = QtGui.QVBoxLayout(self.verticalLayoutWidget_22)
        self.verticalLayout_27.setMargin(0)
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.label_22 = QtGui.QLabel(self.verticalLayoutWidget_22)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_27.addWidget(self.label_22)
        self.doubleSpinBox_23 = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_22)
        self.doubleSpinBox_23.setReadOnly(True)
        self.doubleSpinBox_23.setDecimals(1)
        self.doubleSpinBox_23.setSingleStep(0.1)
        self.doubleSpinBox_23.setProperty("value", 0.0)
        self.doubleSpinBox_23.setObjectName(_fromUtf8("doubleSpinBox_23"))
        self.verticalLayout_27.addWidget(self.doubleSpinBox_23)
        self.verticalLayoutWidget_18 = QtGui.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_18.setGeometry(QtCore.QRect(240, 140, 81, 68))
        self.verticalLayoutWidget_18.setObjectName(_fromUtf8("verticalLayoutWidget_18"))
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.verticalLayoutWidget_18)
        self.verticalLayout_23.setMargin(0)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.label_18 = QtGui.QLabel(self.verticalLayoutWidget_18)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_23.addWidget(self.label_18)
        self.spinBox_19 = QtGui.QSpinBox(self.verticalLayoutWidget_18)
        self.spinBox_19.setMaximum(999999)
        self.spinBox_19.setProperty("value", 210000)
        self.spinBox_19.setObjectName(_fromUtf8("spinBox_19"))
        self.verticalLayout_23.addWidget(self.spinBox_19)
        self.verticalLayoutWidget_20 = QtGui.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_20.setGeometry(QtCore.QRect(20, 250, 81, 68))
        self.verticalLayoutWidget_20.setObjectName(_fromUtf8("verticalLayoutWidget_20"))
        self.verticalLayout_25 = QtGui.QVBoxLayout(self.verticalLayoutWidget_20)
        self.verticalLayout_25.setMargin(0)
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.label_20 = QtGui.QLabel(self.verticalLayoutWidget_20)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_25.addWidget(self.label_20)
        self.doubleSpinBox_21 = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_20)
        self.doubleSpinBox_21.setReadOnly(True)
        self.doubleSpinBox_21.setDecimals(3)
        self.doubleSpinBox_21.setSingleStep(0.001)
        self.doubleSpinBox_21.setObjectName(_fromUtf8("doubleSpinBox_21"))
        self.verticalLayout_25.addWidget(self.doubleSpinBox_21)
        self.verticalLayoutWidget_13 = QtGui.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(20, 30, 81, 68))
        self.verticalLayoutWidget_13.setObjectName(_fromUtf8("verticalLayoutWidget_13"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_18.setMargin(0)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget_13)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_18.addWidget(self.label_13)
        self.spinBox_13 = QtGui.QSpinBox(self.verticalLayoutWidget_13)
        self.spinBox_13.setMaximum(99999)
        self.spinBox_13.setProperty("value", 900)
        self.spinBox_13.setObjectName(_fromUtf8("spinBox_13"))
        self.verticalLayout_18.addWidget(self.spinBox_13)
        self.verticalLayoutWidget_16 = QtGui.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(20, 140, 81, 68))
        self.verticalLayoutWidget_16.setObjectName(_fromUtf8("verticalLayoutWidget_16"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.verticalLayoutWidget_16)
        self.verticalLayout_21.setMargin(0)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.label_16 = QtGui.QLabel(self.verticalLayoutWidget_16)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_21.addWidget(self.label_16)
        self.spinBox_17 = QtGui.QSpinBox(self.verticalLayoutWidget_16)
        self.spinBox_17.setReadOnly(True)
        self.spinBox_17.setObjectName(_fromUtf8("spinBox_17"))
        self.verticalLayout_21.addWidget(self.spinBox_17)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(230, 520, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 560, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "压力管道设计", None))
        self.groupBox.setTitle(_translate("MainWindow", "管径", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>管径D</p><p>(mm)</p></body></html>", None))
        self.spinBox_1.setSpecialValueText(_translate("MainWindow", "0", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "抗压稳定性要求", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>弹性模量</p><p>(N/mm<span style=\" vertical-align:super;\">2</span>)</p></body></html>", None))
        self.spinBox_4.setSpecialValueText(_translate("MainWindow", "0", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>钢管外压</p><p>(MPa)</p></body></html>", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aa00;\">临界外压P</span><span style=\" color:#00aa00; vertical-align:sub;\">cr</span></p><p><span style=\" color:#00aa00;\">(MPa)</span></p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aa00;\">计算壁厚δ</span></p><p><span style=\" color:#00aa00;\">(mm)</span></p></body></html>", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aa00;\">结构壁厚δ</span><span style=\" color:#00aa00; vertical-align:sub;\">0</span></p><p><span style=\" color:#00aa00;\">(mm)</span></p></body></html>", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "抗内压强度要求", None))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>设计压力</p><p>(MPa)</p></body></html>", None))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aa00;\">计算壁厚δ</span></p><p><span style=\" color:#00aa00;\">(mm)</span></p></body></html>", None))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aa00;\">结构壁厚δ</span><span style=\" color:#00aa00; vertical-align:sub;\">0</span></p><p><span style=\" color:#00aa00;\">(mm)</span></p></body></html>", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "构造要求", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aa00;\">D/800+4</span></p><p><span style=\" color:#00aa00;\">(mm)</span></p></body></html>", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>最小结构壁厚</p><p>(mm)</p></body></html>", None))
        self.spinBox_3.setSpecialValueText(_translate("MainWindow", "0", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "壁厚取值", None))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aa00;\">壁厚取值</span></p><p><span style=\" color:#00aa00;\">(mm)</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "壁厚计算", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "加劲环后抗压稳定计算", None))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p>结构壁厚δ<span style=\" vertical-align:sub;\">0</span></p><p>(mm)</p></body></html>", None))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p>假定n</p><p>试算P<span style=\" vertical-align:sub;\">cr</span></p></body></html>", None))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p>加劲环间距l</p><p>(mm)</p></body></html>", None))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aa00;\">计算壁厚δ</span></p><p><span style=\" color:#00aa00;\">(mm)</span></p></body></html>", None))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p>泊松比</p><p>μ</p></body></html>", None))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p>钢管外压</p><p>(MPa)</p></body></html>", None))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aa00;\">安全系数</span></p><p><span style=\" color:#00aa00;\">.</span></p></body></html>", None))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p>弹性模量</p><p>(N/mm<span style=\" vertical-align:super;\">2</span>)</p></body></html>", None))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aa00;\">临界外压P</span><span style=\" color:#00aa00; vertical-align:sub;\">cr</span></p><p><span style=\" color:#00aa00;\">（MPa）</span></p></body></html>", None))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p>管径D</p><p>(mm)</p></body></html>", None))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aa00;\">屈曲波数</span></p><p><span style=\" color:#00aa00;\">n</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "设加劲环后抗压稳定计算", None))
        self.pushButton.setText(_translate("MainWindow", "计算", None))

